# docker compose --env-file ~/.env up -d
version: '3.8'

services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slack_ai_prod
    ports:
      - "30207:30207"
    command: "uvicorn slack_ai.app:app --host 0.0.0.0 --port 30207 --reload"

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slack_ai_dev
    volumes:
      - ./:/slack_ai
    ports:
      - "30207:30207"
    command: "/bin/bash"
    stdin_open: true
    tty: true
