# docker compose --env-file ~/.env up -d
version: '3.8'

services:
  slack_gpt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slack_gpt
    ports:
      - "30207:30207"
    command: "uvicorn slack_gpt.app:app --host 0.0.0.0 --port 30207 --reload"
